baseURL = "https://proactive.activeeon.com/"
#baseURL = "/"
title = "ProActive from Activeeon"
theme = "proactive"
languageCode = "en-us"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-31966922-1"

[params]
  description = "Job Scheduling, Workload Automation, Orchestration & Metascheduling on-premises and on all clouds."
  

[permalinks]
  page = "/:filename/"

[author]
  name = "nicolas narbais"
  

[menu]

# Main menu

[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 10

[[menu.main]]
  name = "Get Started"
  url  = "/get-started/"
  weight = 20

[[menu.main]]
  name = "Community"
  url  = "#"
  identifier = "community"
  weight = 30

[[menu.main]]
  identifier = "product"
  name = "Product"
  url = "#"
  weight = 40

[[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 50

[[menu.main]]
  parent = "community"
  name = "Github & Use Cases"
  url  = "/community/"
  weight = 31

[[menu.main]]
  parent = "community"
  name = "Blog"
  url  = "http://blog.activeeon.com/"
  weight = 32

[[menu.main]]
  parent = "community"
  name = "Hub"
  url  = "http://hub.activeeon.com/"
  weight = 33

[[menu.main]]
  parent = "product"
  name = "Workflows & Scheduling"
  url = "https://www.activeeon.com/workflows-scheduling"
  weight = 41

[[menu.main]]
  parent = "product"
  name = "Big Data Automation"
  url = "https://www.activeeon.com/big-data-automation"
  weight = 42

[[menu.main]]
  parent = "product"
  name = "ML Open Studio"
  url = "/ml-os/"
  weight = 43

[[menu.main]]
  parent = "product"
  name = "Automation Dashboard"
  url = "https://www.activeeon.com/cloud-automation"
  weight = 44

[[menu.main]]
  parent = "product"
  name = "Release Notes"
  url  = "/release-notes/"
  weight = 45

[params.links.activeeon]
  home = "https://www.activeeon.com/"
  contact = "https://www.activeeon.com/about/contact"
  customers = "https://www.activeeon.com/about/customers"
  events = "https://www.activeeon.com/about/news-events"
  try = "https://try.activeeon.com/"
  trystudio = "https://try.activeeon.com/studio/"
  tryscheduler = "https://try.activeeon.com/scheduler/"
  blog = "http://blog.activeeon.com/"
  hub = "http://hub.activeeon.com"
  repoproactive = "http://github.com/ow2-proactive"
  repobugtracker = "https://github.com/ow2-proactive/scheduling/issues"
  doc = "https://www.activeeon.com/public_content/documentation/"
  ow2 = "https://projects.ow2.org/bin/view/proactive/"
